name: Continuous Integration

on:
  pull_request:

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure PR into main is only from develop, release/* or hotfix/*
        if: github.base_ref == 'main'
        run: |
          case "${{ github.head_ref }}" in
            develop|release/*|hotfix/*) ;;
            *)
              echo "‚ùå Pull Requests to 'main' are only allowed from 'develop', 'release/*', or 'hotfix/*' branches."
              exit 1
              ;;
          esac

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@19

      - name: Build
        run: |
          ng build angular-components
          npm run build:lib
